version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    registry: https://registry.npmjs.org/
    auth:
      username: santhosh270
      password: Catalyst@test123

jobs:
  Deploy_Appsail:
    runner: Machine
    image: image
    steps:
      - npm install -g zcatalyst-cli
      - catalyst --version
      - npm install
      - catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
stages:
  - name: test
    jobs:
      - Deploy_Appsail