version: 1
runners:
  Machine:
    config-id: 3

jobs:
  build-chatrail:    
    steps:
      - chmod +x new_build.sh
      - ./new_build.sh --deploy\
    runner: Machine
stages:
  - name: build
    jobs:
      - build-chatrail