version: 1.0
runners:
  Machine:
    config-id: 3
jobs:
  build-chatrail:
    steps:
      - chmod +x new_build.sh
      - ./new_build.sh --deploy\
stages:
  - name: build
    jobs:
      - build-chatrail

pipeline-runner: Machine