version: 1
runners:
  Machine:
    config-id: 3

jobs:
  build-chatrail: 
    runner: Machine   
    steps:
      - chmod +x new_build.sh
      - ./new_build.sh --deploy\
stages:
  - name: build
    jobs:
      - build-chatrail