version: 1
runners:
  Machine:
    config-id: 2

jobs:
  Deploy_Appsail:
    runner: Machine
    steps:
      - node --version  
      - catalyst --version
      - npm install -g zcatalyst-cli
      - catalyst --version
      - npm install
      - catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
stages:
  - name: test
    jobs:
      - Deploy_Appsail